#!/usr/bin/env node
/**
 * wix-cms.mjs  —  Wix + Claude Addon (CMS schema bridge)
 *
 * An external agent writing Velo `wix-data` queries is blind to the site's CMS:
 * it doesn't know which collections exist or their field keys/types, so it
 * guesses field names and writes queries that silently return nothing. This
 * lists every Data Collection + field schema via the Wix Data REST API into
 * committed, agent-readable artifacts at the repo root:
 *
 *   - wix-cms.json   (machine-readable: collections + fields + permissions)
 *   - wix-cms.md     (tables per collection, with a ready-to-paste query)
 *   - updates the WIX-CMS block inside CLAUDE.md (if present)
 *
 * Needs a Wix API key with the "Manage Data Collections" permission (the only
 * documented scope; this tool only ever issues read-only GETs). Creds come from
 * env or a gitignored .env: WIX_API_KEY + WIX_SITE_ID (site id falls back to
 * wix.config.json) — the same setup as `wix:media`.
 *
 * Usage:
 *   node scripts/wix-cms.mjs [--repo <path>] [--out <path>] [--quiet] [--soft]
 */

import { readFileSync, writeFileSync, existsSync, mkdirSync } from 'node:fs';
import { join } from 'node:path';
import { parseDotenv } from './wix-media-lib.mjs';
import { normalizeCollection, listCollections, renderCmsMarkdown, renderClaudeCmsBlock } from './wix-cms-lib.mjs';

// ─── args ────────────────────────────────────────────────────────────────────
const argv = process.argv.slice(2);
const arg = (n, d) => { const i = argv.indexOf(n); return i !== -1 && argv[i + 1] ? argv[i + 1] : d; };
const REPO = arg('--repo', process.cwd());
const OUT = arg('--out', REPO);
const QUIET = argv.includes('--quiet');
const SOFT = argv.includes('--soft'); // never exit non-zero (postinstall / chained use)
const log = (...a) => { if (!QUIET) console.log(...a); };

mkdirSync(OUT, { recursive: true });
const readIf = (p) => { try { return readFileSync(p, 'utf8'); } catch { return null; } };

function resolveCreds() {
  const envFiles = { ...parseDotenv(readIf(join(REPO, '.env'))), ...parseDotenv(readIf(join(REPO, 'headless', '.env'))) };
  const apiKey = process.env.WIX_API_KEY || envFiles.WIX_API_KEY || null;
  let siteId = process.env.WIX_SITE_ID || envFiles.WIX_SITE_ID || null;
  if (!siteId) { try { siteId = (JSON.parse(readIf(join(REPO, 'wix.config.json')) || '{}').siteId) || null; } catch {} }
  return { apiKey, siteId };
}

async function main() {
  log(`\n🗄  wix-cms  (repo: ${REPO})`);

  let collections = [], truncated = false, error = null, source = 'not configured (no API key)';
  const { apiKey, siteId } = resolveCreds();
  if (apiKey && siteId) {
    log(`• listing Data Collections via REST (site ${siteId}) …`);
    const res = await listCollections({ apiKey, siteId, fetchImpl: fetch, log });
    collections = res.collections.map(normalizeCollection).filter(Boolean);
    truncated = res.truncated; error = res.error || null;
    source = error ? 'Wix Data REST API (partial)' : 'Wix Data REST API';
    if (error) {
      const hint = error.code === 401 || error.code === 403
        ? ' (check the API key has the "Manage Data Collections" permission + WIX_SITE_ID)'
        : error.code === 429 ? ' (rate-limited — wait a minute and retry)' : '';
      log(`  ✗ ${error.message}${hint}`);
    }
    log(`  ✓ ${collections.length} collection(s)`);
  } else {
    log('• no WIX_API_KEY/WIX_SITE_ID found — writing a setup stub instead of a listing.');
    log('    Add them in a .env (gitignored) + grant the key "Manage Data Collections". See docs/wix-addon/CMS.md.');
  }

  let site = {};
  try { site = JSON.parse(readIf(join(REPO, 'wix.config.json')) || '{}'); } catch {}

  const fieldsTotal = collections.reduce((n, c) => n + c.fieldCount, 0);
  const stats = {
    collections: collections.length,
    fields: fieldsTotal,
    native: collections.filter(c => c.collectionType === 'NATIVE').length,
    app: collections.filter(c => c.collectionType !== 'NATIVE').length,
  };
  const generatedAt = new Date().toISOString();
  const model = { generatedAt, source, truncated, error, site: { siteId: site.siteId ?? siteId ?? null }, stats, collections };

  const json = {
    $note: 'AUTO-GENERATED by scripts/wix-cms.mjs. Do not edit by hand. Use a collection id in wixData.query("…") and a field key in .eq("…",…). Read-only listing.',
    generatedAt, source, truncated, error: error ? error.message : null,
    site: model.site, stats, collections,
  };
  writeFileSync(join(OUT, 'wix-cms.json'), JSON.stringify(json, null, 2));
  writeFileSync(join(OUT, 'wix-cms.md'), renderCmsMarkdown(model));

  const claudePath = join(OUT, 'CLAUDE.md');
  const claude = readIf(claudePath);
  if (claude && collections.length) {
    const START = '<!-- WIX-CMS:START -->';
    const END = '<!-- WIX-CMS:END -->';
    const block = renderClaudeCmsBlock(model, { start: START, end: END });
    const next = claude.includes(START) && claude.includes(END)
      ? claude.replace(new RegExp(START + '[\\s\\S]*?' + END), block)
      : claude.trimEnd() + '\n\n' + block + '\n';
    writeFileSync(claudePath, next);
    log('[wix-cms] updated CLAUDE.md CMS block');
  }

  log(`[wix-cms] wrote ${join(OUT, 'wix-cms.json')}`);
  log(`[wix-cms] wrote ${join(OUT, 'wix-cms.md')}`);
  log(`[wix-cms] ${stats.collections} collections · ${stats.fields} fields (source: ${source})`);
}

main().catch((e) => {
  console.error('[wix-cms] error: ' + (e?.stack || e?.message || e));
  process.exit(SOFT ? 0 : 1);
});
